using System.Runtime.InteropServices;

namespace SimLab.Models;

[StructLayout(LayoutKind.Sequential, Pack = 4)]
public struct DirtRallyUdpData
{
    public float RunTime;
    public float LapTime;
    public float Distance;
    public float Progress;
    public float PosX;
    public float PosY;
    public float PosZ;
    public float Speed;
    public float VelX;
    public float VelY;
    public float VelZ;
    public float RightX;
    public float RightY;
    public float RightZ;
    public float ForwardX;
    public float ForwardY;
    public float ForwardZ;
    public float SuspensionPositionRL;
    public float SuspensionPositionRR;
    public float SuspensionPositionFL;
    public float SuspensionPositionFR;
    public float SuspensionVelocityRL;
    public float SuspensionVelocityRR;
    public float SuspensionVelocityFL;
    public float SuspensionVelocityFR;
    public float WheelSpeedRL;
    public float WheelSpeedRR;
    public float WheelSpeedFL;
    public float WheelSpeedFR;
    public float Throttle;
    public float Steering;
    public float Brake;
    public float Clutch;
    public float Gear;
    public float GForceLat;
    public float GForceLon;
    public float Lap;
    public float EngineRPM;
    public float SliProSupport;
    public float RacePos;
    public float KersLevel;
    public float KersMaxLevel;
    public float Drs;
    public float TractionControl;
    public float AntiLockBrakes;
    public float FuelInTank;
    public float FuelCapacity;
    public float InPit;
    public float Sector;
    public float Sector1Time;
    public float Sector2Time;
    public float BrakesTempRL;
    public float BrakesTempRR;
    public float BrakesTempFL;
    public float BrakesTempFR;
    public float TirePressureRL;
    public float TirePressureRR;
    public float TirePressureFL;
    public float TirePressureFR;
    public float LapsCompleted;
    public float TotalLaps;
    public float TrackLength;
    public float LastLapTime;
    public float MaxRPM;
    public float IdleRPM;
    public float MaxGears;
}
